version: "3.9"

services:
  backend:
    build: ${PROJECT_DIR}/builds/backend
    image: maps/backend:${RAPYDO_VERSION}
    environment:
      PLATFORM: ${PLATFORM}
      ALLOWED_IPS: ${ALLOWED_IPS}
      GEOSERVER_ADMIN_USER: ${GEOSERVER_ADMIN_USER}
      GEOSERVER_ADMIN_PASSWORD: ${GEOSERVER_ADMIN_PASSWORD}
      WW3_DATA_PATH: ${WW3_DATA_PATH}
      SEASONAL_DATA_PATH: ${SEASONAL_DATA_PATH}
      RADAR_DATA_PATH: ${RADAR_DATA_PATH}
      SUB_SEASONAL_DATA_PATH: ${SUB_SEASONAL_DATA_PATH}
      WINDY_MULTILAYER_DATA_PATH: ${WINDY_DATA_PATH}
    volumes:
      - ${HOST_WINDY_GEOTIFF_DIR}:${WINDY_DATA_PATH}
      - ${STATIC_MAPS_DATA_PATH}:${DATA_PATH}
      - ${HOST_SEASONAL_GEOTIFF_DIR}:/seasonal-aim
      - ${HOST_RADAR_DIR}:${RADAR_DATA_PATH}
      - ${HOST_SUB_SEASONAL_GEOTIFF_DIR}:${SUB_SEASONAL_DATA_PATH}
      - ${HOST_WW3_DIR}:/ww3
  celery:
    build: ${PROJECT_DIR}/builds/backend
    image: maps/backend:${RAPYDO_VERSION}
    environment:
      PLATFORM: ${PLATFORM}
      GEOSERVER_ADMIN_USER: ${GEOSERVER_ADMIN_USER}
      GEOSERVER_ADMIN_PASSWORD: ${GEOSERVER_ADMIN_PASSWORD}
      RADAR_RETENTION_HOURS: ${RADAR_RETENTION_HOURS}
      WW3_DATA_PATH: ${WW3_DATA_PATH}
      SEASONAL_DATA_PATH: ${SEASONAL_DATA_PATH}
      RADAR_DATA_PATH: ${RADAR_DATA_PATH}
      SUB_SEASONAL_DATA_PATH: ${SUB_SEASONAL_DATA_PATH}
    volumes:
      - ${HOST_WINDY_GEOTIFF_DIR}:/windy
      - ${HOST_SEASONAL_GEOTIFF_DIR}:${SEASONAL_DATA_PATH}
      - ${DATA_DIR}/geoserver_data:/geoserver_data
      - ${DATA_DIR}/../projects/maps/builds/geoserver/SLDs:/SLDs
      - ${HOST_RADAR_DIR}:${RADAR_DATA_PATH}
      - ${HOST_SUB_SEASONAL_GEOTIFF_DIR}:${SUB_SEASONAL_DATA_PATH}
      - ${HOST_WW3_DIR}:/ww3
      - ${DATA_DIR}/celery_health:/status
  celerybeat:
    build: ${PROJECT_DIR}/builds/backend
    image: maps/backend:${RAPYDO_VERSION}
  thredds:
    # environment:
    #   - JAVA_OPTS=-Xmx2g
    # image: unidata/thredds-docker:5.6
    build: ${PROJECT_DIR}/builds/thredds
    image: sdl/thredds:${RAPYDO_VERSION}
    command: >
      "chmod a+x ./init.sh; ./init.sh"
    ports:
      - "8081:8080"
    volumes:
      # - ${DATA_DIR}/tds/tomcat/logs/:/usr/local/tomcat/logs/
      # - ${DATA_DIR}/tds/thredds/logs/:/usr/local/tomcat/content/thredds/logs/
      # - ${DATA_DIR}/tds/tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      # - ${DATA_DIR}/tds/thredds/catalog:/usr/local/tomcat/content/thredds
      - ${DATA_DIR}/maps:/usr/local/tomcat/content/thredds/public/testdata
    environment:
      ACTIVATE: ${ACTIVATE_THREDDS}
      # TDS Content root
      TDS_CONTENT_ROOT_PATH: /usr/local/tomcat/content
      # The minimum and maximum Java heap space memory to be allocated to the TDS
      THREDDS_XMX_SIZE: 4G
      THREDDS_XMS_SIZE: 4G
      TDS_HOST: ${PROJECT_DOMAIN}
      # See https://github.com/Unidata/tomcat-docker#configurable-tomcat-uid-and-gid
      TOMCAT_USER_ID: ${CURRENT_UID}
      TOMCAT_GROUP_ID: ${CURRENT_GID}
    networks:
      default:
        aliases:
          - thredds.dockerized.io

  geoserver:
    image: meteo-hub-geoserver:${PROJECT_VERSION}
    restart: unless-stopped
    build:
      context: ${PROJECT_DIR}/builds/geoserver
      args:
        GEOSERVER_UID: ${CURRENT_UID}
        GEOSERVER_GID: ${CURRENT_GID}
        IMAGE_VERSION: 9.0-jdk11-openjdk-slim-buster
    # image: docker.osgeo.org/geoserver:2.26.1
    # build:
    #   context: ${PROJECT_DIR}/builds/geoserver
    #   args:
    #     GEOSERVER_UID: ${CURRENT_UID}
    #     GEOSERVER_GID: ${CURRENT_GID}
    #     IMAGE_VERSION: 9.0-jdk11-openjdk-slim-buster
    ports:
      - "8081:8080"
    environment:
      ACTIVATE: ${ACTIVATE_GEOSERVER}
      # STABLE_EXTENSIONS: netcdf-plugin
      TOMCAT_EXTRAS: false
      EXISTING_DATA_DIR: ${GEOSERVER_EXISTING_DATA_DIR}
      GEOSERVER_ADMIN_USER: ${GEOSERVER_ADMIN_USER}
      GEOSERVER_ADMIN_PASSWORD: ${GEOSERVER_ADMIN_PASSWORD}
      RECREATE_DATADIR: ${GEOSERVER_RECREATE_DATADIR}
      # JAVA_OPTS: "-Xms512m -Xmx1024m -Duser.timezone=GMT -Dorg.geotools.shapefile.datetime=true"
      JAVA_OPTS: "-Xms512m -Xmx1024m -Duser.timezone=GMT -Dorg.geotools.shapefile.datetime=true"
      # JAVA_OPTS: "-Xms512m -Xmx1024m -DNETCDF_DATA_DIR=/opt/geoserver_data"
    volumes:
      - ${DATA_DIR}/geoserver_data:/opt/geoserver_data
      # - ${DATA_DIR}/geoserver/settings:/settings
    healthcheck:
      test: 
        - "CMD-SHELL"
        - "curl -f 'http://localhost:8080/geoserver/wms?service=WMS&request=GetMap&layers=meteohub:t2m-t2m&styles=&format=image/png&version=1.1.1&width=256&height=256&srs=EPSG:3857&bbox=0,5009377.085697314,2504688.5428486555,7514065.628545967' | if grep -q 'ServiceException'; then exit 1; else exit 0; fi"
      interval: 30s
          # curl -f "$(cat $$CATALINA_HOME/conf/healthcheck_url.txt)" && \
      timeout: 10s
      retries: 3
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "100m"         # Maximum log size (100 MB in this case)
        max-file: "3"           # Retain 3 log files before older ones are deleted
    networks:
      default:
        aliases:
          - geoserver.dockerized.io

  healthwatch:
    image: docker:cli
    container_name: healthwatch
    environment:
      ACTIVATE: ${ACTIVATE_GEOSERVER}

    depends_on:
      - geoserver
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DATA_DIR}/celery_health:/celery/status
    command: |
      sh -c '
      echo "Waiting for maps-geoserver-1..."
      until docker ps > /dev/null 2>&1; do sleep 1; done
      sleep 30
      while true; do
        STATUS=$$(docker inspect --format="{{.State.Health.Status}}" maps-geoserver-1 2>/dev/null)
        echo "Geoserver status: $$STATUS"
        if [ "$$STATUS" = "unhealthy" ] || [ -n "$$(ls -A /celery/status 2>/dev/null)" ]; then
          rm -f /celery/status/*
          echo "Restarting geoserver due to unhealthy status..." >&2
          docker stop maps-celery-1
          docker restart maps-geoserver-1
          sleep 120
          docker restart maps-celery-1
        fi
        sleep 10
      done
      '