"""Generate and refresh nginx's maintenance IP gate from the shared status file."""

import argparse
import ipaddress
import json
import logging
import os
import re
import subprocess
import time
from pathlib import Path

log = logging.getLogger("nginx-maintenance")
GUARD = "\n    if ($meteohub_maintenance_denied) { return 503; }\n"


def networks(value: str) -> list[str]:
    """Validate IPs/CIDRs before interpolating them into nginx configuration."""
    return list(
        dict.fromkeys(
            str(ipaddress.ip_network(item, strict=False))
            for item in re.split(r"[\s,]+", value.strip())
            if item
        )
    )


def render_configuration(active: bool, allowlist: str, trusted_proxies: str) -> str:
    lines = ["# Generated by MeteoHub maintenance.py; do not edit."]
    for network in networks(trusted_proxies):
        lines.append(f"set_real_ip_from {network};")
    if trusted_proxies.strip():
        lines.extend(["real_ip_header X-Forwarded-For;", "real_ip_recursive on;"])
    lines.extend(["geo $meteohub_maintenance_allowed {", "    default 0;"])
    lines.extend(f"    {network} 1;" for network in networks(allowlist))
    lines.extend(
        [
            "}",
            "map $host $meteohub_maintenance_active {",
            f"    default {int(active)};",
            "}",
            'map "$meteohub_maintenance_active:$meteohub_maintenance_allowed" '
            "$meteohub_maintenance_denied {",
            "    default 0;",
            '    "1:0" 1;',
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def maintenance_active(status_file: Path, previous: bool = False) -> bool:
    """Retain the last state during missing, malformed or unreadable updates."""
    try:
        status = json.loads(status_file.read_text())
        if not isinstance(status, dict) or status.get("status") not in (
            "operational",
            "maintenance",
            "degraded",
            "outage",
        ):
            raise ValueError("invalid system status")
        return status["status"] == "maintenance"
    except FileNotFoundError:
        return previous
    except (OSError, ValueError):
        log.warning("Cannot read maintenance status; retaining the last nginx state")
        return previous


def guard_templates(template_dir: Path) -> None:
    """Apply the gate at server rewrite phase, before location returns/proxying."""
    for template in template_dir.glob("*.conf"):
        text = template.read_text()
        if "$meteohub_maintenance_denied" in text:
            continue
        guarded = re.sub(r"(?m)^(\s*server\s*\{)", r"\1" + GUARD, text)
        if guarded != text:
            template.write_text(guarded)


def write_configuration(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(".tmp")
    temporary.write_text(content)
    temporary.replace(path)


def sync_configuration(path: Path, content: str, *, reload: bool) -> bool:
    """Validate before reloading; roll back if nginx cannot accept the update."""
    old = path.read_text() if path.exists() else None
    if old == content:
        return True
    write_configuration(path, content)
    if not reload:
        return True
    try:
        subprocess.run(["nginx", "-t"], check=True, capture_output=True)
        subprocess.run(["nginx", "-s", "reload"], check=True, capture_output=True)
    except subprocess.CalledProcessError as error:
        log.error("Cannot reload maintenance gate: %s", error.stderr.decode())
        if old is not None:
            write_configuration(path, old)
        else:
            path.unlink()
        return False
    log.info("Updated nginx maintenance gate")
    return True


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("action", choices=("prepare", "watch"))
    args = parser.parse_args()
    logging.basicConfig(level=logging.INFO)
    allowlist = os.environ.get("MAINTENANCE_ALLOWLIST", "")
    trusted_proxies = os.environ.get("MAINTENANCE_TRUSTED_PROXIES", "")
    # Invalid addresses fail startup rather than generating nginx directives.
    networks(allowlist)
    networks(trusted_proxies)
    forced = os.environ.get("MAINTENANCE_MODE", "").strip()
    if forced not in ("", "0", "1"):
        raise ValueError("MAINTENANCE_MODE must be empty, 0 or 1")
    status_file = Path(
        os.environ.get("STATUS_FILE_PATH", "/var/lib/meteohub/status.json")
    )
    configuration = Path("/etc/nginx/sites-enabled/00-maintenance.preconf")
    active = maintenance_active(status_file) if not forced else forced == "1"
    if args.action == "prepare":
        guard_templates(Path("/etc/nginx/sites-enabled-templates"))
        sync_configuration(
            configuration,
            render_configuration(active, allowlist, trusted_proxies),
            reload=False,
        )
        return
    # Preparation already recorded the initial state. Preserve it on read errors.
    if configuration.exists():
        active = "default 1;" in configuration.read_text()
    while True:
        desired = (
            maintenance_active(status_file, active) if not forced else forced == "1"
        )
        # The original entrypoint may still be generating certificates/configs.
        if Path("/var/run/nginx.pid").exists():
            if sync_configuration(
                configuration,
                render_configuration(desired, allowlist, trusted_proxies),
                reload=True,
            ):
                active = desired
        time.sleep(1)


if __name__ == "__main__":
    main()
